backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/post
    label: "Posts" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "static/img/" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", summary: "{{fields.tag}}", field: { label: "Tag", name: "tag", widget: "string" }} # https://github.com/decaporg/decap-cms/issues/4646 
      - { label: "Body", name: "body", widget: "markdown", hint: "Make sure to name added image as thumbnail" }
